<a href="https://colab.research.google.com/github/DCI-alxogm/ml2023-proditorIF/blob/main/Ago11-12/Numpy_Rep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notebook_01 Machine Learning UG / Alma
>  **Barush Michelle Rueda Muñoz**

>Contenido:Repaso de Numpy



In [2]:
import numpy as np

**Arreglos**

In [79]:
#Fixed type data structure
V = np.array([2,3,4])
#Arrays can be multimiensional data structures
v2= np.array([V,[0,1,0],[3,8,2]]) #Type of matrix
#special comands to create specificall arrays
oz = np.zeros(5) #Array of zeros
n1= np.ones((3,3)) #3x3 matrix of ones
piq= np.full((2,3),3.1416) #Multidimensional structure filled with an specific digit
# Similar to the range data structure
sec = np.arange(0,15,3) #Starting at 0, ending at 15, stepping by 3
#evenly spaced  array
ev = np.linspace(0,2,10) #evenly spaced  digtis between 0 and 1
#Random structure
rand = np.random.random((2,2)) #Uniformly distributed random values between 0 and 1
#Structure of normally distributed random values
randn = np.random.normal(2,0.8,(3,3)) # with mean 2 and standard deviation 0.8
#Random structure of integrs in an specific interval
esran = np.random.randint(0,7,(3,3))
#identity Matrix
i3 = np.eye(3)
# Three dimensional array
trek = np.random.randint(10,size=(3,2,2)) #Each compoent of the array is a matrix
print(trek)
#Access to an specific element
lisT = np.array([9,2,7,4])
print("Elemento 1 =",lisT[0])
lisT2  = np.random.randint(0,7,(2,2))
print("Elemento (0,1)=",lisT2[0,1])
#3d
lisT3  = np.random.randint(0,7,(2,2,2))
print("Elemento (0,0,1)=",lisT3[0,0,1])
#Slice
x = np.arange(10)
print("Primeros 3 elementos=",x[:3])
print("ultimos 3 elementos=",x[7:])
print("3 elementos=",x[3:6])
print("Pares=",x[0::2])
print("Arreglo inverido=",x[::-1])
#Multidemsinal slice
x2=np.array([np.arange(3),np.arange(3),np.arange(3)])
print(" 2x2=",x2[:2,:2])
#Inverted in multiple dimensions
print("\n Inverted in multiple dimensions=",x2[::-1,::-1])
x3=np.array([[np.arange(3),np.arange(3)],[np.arange(3),np.arange(3)],[np.arange(3),np.arange(3)]])
print ("\n Vector of matrixs\n",x3)
mmr = np.random.randint(0,3,(3,3,3,3))
print ("\n Metrix of matrixs\n",mmr)
#Rows and culum access
tra = np.array([[0,1,2],[3,4,5],[6,7,8]])
print("Matriz 3x3\n",tra)
print("Primera fila\n",tra[0,:])
print("Primera columna\n",tra[:,0])


[[[9 0]
  [4 7]]

 [[1 4]
  [9 9]]

 [[4 4]
  [1 8]]]
Elemento 1 = 9
Elemento (0,1)= 2
Elemento (0,0,1)= 4
Primeros 3 elementos= [0 1 2]
ultimos 3 elementos= [7 8 9]
3 elementos= [3 4 5]
Pares= [0 2 4 6 8]
Arreglo inverido= [9 8 7 6 5 4 3 2 1 0]
 2x2= [[0 1]
 [0 1]]

 Inverted in multiple dimensions= [[2 1 0]
 [2 1 0]
 [2 1 0]]

 Vector of matrixs
 [[[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]]

 Metrix of matrixs
 [[[[2 1 1]
   [2 2 0]
   [1 0 0]]

  [[2 0 1]
   [1 1 0]
   [1 1 0]]

  [[1 1 1]
   [1 2 0]
   [0 1 2]]]


 [[[2 0 1]
   [0 0 2]
   [2 1 1]]

  [[2 2 1]
   [2 2 1]
   [1 0 2]]

  [[1 0 2]
   [1 0 1]
   [1 1 1]]]


 [[[0 1 2]
   [1 2 1]
   [0 2 0]]

  [[2 2 0]
   [1 2 2]
   [2 0 1]]

  [[1 0 0]
   [1 2 0]
   [2 1 0]]]]
Matriz 3x3
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Primera fila
 [0 1 2]
Primera columna
 [0 3 6]
Transpuesta
 [[8 7 6]
 [5 4 3]
 [2 1 0]]
